KPUS-2 Add feature to get push notifications for voicemail updates
2600hz/kazoo-pusher pull request #16
Opened 2022-11-16 16:47 UTC by wdhammika

Previously, There were no voicemail updates sent to the client's IOS/Android device/s.
Now, A push notification will deliver to the Client's IOS/Android device when there is a voicemail update.

Preconditions: The device should have the push capability and it should be enabled.
			An application should have registered in pusher in order to capture push requests on the device.

2022-11-16 18:30 UTC, lazedo requested changes

2022-11-16 18:30 UTC, lazedo commented on src/pusher.hrl
> +-endif.
you're not changing anything, undo this change

2022-11-16 18:30 UTC, lazedo commented on src/pusher_listener.erl
> +    gen_listener:cast(?MODULE, {'push', JObj}).
you're not changing anything, undo this change

2022-11-16 18:30 UTC, lazedo commented on src/pusher_shared_listener.erl
> +                  ,{'self', []}
is there a reason to subscribe to `self` ?

2022-11-16 18:30 UTC, lazedo commented on src/pusher_shared_listener.erl
> +                     }
you can add pusher_voicremail_notification directly, no need to handle it on this module, also, instead of * *, handle the specific category/event

2022-11-16 18:30 UTC, lazedo commented on src/pusher_shared_listener.erl
> +    end.
no need for this fun

2022-11-16 18:30 UTC, lazedo commented on src/pusher_voicemail_notification.erl
> +%%% @author Wimal Dhammika
undo this

2022-11-16 18:30 UTC, lazedo commented on src/pusher_voicemail_notification.erl
> +              ,{<<"Call-ID">>, CallId}
why are these needed ?

2022-11-16 18:30 UTC, lazedo commented on src/pusher_voicemail_notification.erl
> +    end.
fix this

2022-11-16 18:53 UTC, wdhammika commented on src/pusher.hrl
> +-endif.
Reverted the change.

2022-11-16 18:54 UTC, wdhammika commented on src/pusher_listener.erl
> +    gen_listener:cast(?MODULE, {'push', JObj}).
Reverted the change.

2022-11-24 15:52 UTC, wdhammika commented on src/pusher_shared_listener.erl
> +                  ,{'self', []}
This has been removed with the latest pull request.

2022-11-24 15:52 UTC, wdhammika commented on src/pusher_shared_listener.erl
> +                     }
Fixed it.

2022-11-24 15:52 UTC, wdhammika commented on src/pusher_shared_listener.erl
> +    end.
Removed the function.

2022-11-24 15:54 UTC, wdhammika commented on src/pusher_voicemail_notification.erl
> +              ,{<<"Call-ID">>, CallId}
Verizon does not have a specific payload for this requirement. So I have used the payload of MWI updates for this development.

2022-12-12 17:45 UTC, merged