KPUS-4: implement generic push notification mechanism
2600hz/kazoo-pusher pull request #19
Opened 2022-12-13 19:07 UTC by danielfinke

- add `endpoint_push_req` for sending generic push notifications
  - enables sending to an individual device or all push-enabled devices
    for a user
  - covers common push payload props between APNs/FCM
  - covers some select unique push payload props on APNs or FCM
- generic push payloads/headers using keypath map
- move `pm_*` module lookups to binaries to avoid exposing atom table
- convert legacy `push_req`s into `endpoint_push_req`s to avoid dual
  implementations
  - maintain compatibility features such as merging push app extra
    headers/envelope when building payloads

## Related PRs
- https://github.com/2600hz/kazoo-core/pull/555

2022-12-13 19:09 UTC, danielfinke commented
@lazedo requesting your review on this, since I've made some changes to the incoming call notifications. To avoid having 2 different implementations in `pm_apple`/`pm_firebase`, I am converting `push_req`s into `endpoint_push_req`s before sending them to the modules.

2022-12-13 22:24 UTC, harenson requested changes

2022-12-13 22:24 UTC, harenson commented on src/pusher_listener.erl
> +    Definition = kapi_pusher:endpoint_push_req_definition(),
Use `kapi_pusher:api_definition(<<"endpoint_push_req">>)` instead.

2022-12-13 22:24 UTC, harenson commented on src/pusher_listener.erl
> +                                       ], Data);
Improve readability by adding a new line here, to make it easier to see the 2 parameters' function call.

2022-12-13 22:24 UTC, harenson commented on src/pusher_listener.erl
> +                       ], JObj1).
Improve readability by adding a new line here, to make it easier to see the 2 parameters' function call.

2022-12-13 22:24 UTC, harenson commented on src/pusher_listener.erl
> +                       ], JObj1).
This function could have some tests ;)

2022-12-13 22:24 UTC, harenson commented on src/pusher_module_util.erl
> +    build_payload(FlatProps, JObj, GetKeyMap, Acc1).
This function could have some tests ;)

2022-12-16 04:44 UTC, danielfinke commented
@harenson I added EUnit tests for both functions. They are failing in CI right now, though, because they depend on the `kazoo-core` changes.

2022-12-28 21:59 UTC, merged