KPUS-6 Add kazoo device id and message type into push payload.
2600hz/kazoo-pusher pull request #30
Opened 2023-06-22 03:06 UTC by wdhammika

Previously, the push message payload included no push message type and Kazoo device id. Therefore this development is related to adding those parameters to push payload.

Preconditions: The device should have the push capability and it should be enabled.
An application should have registered in Pusher in order to capture push requests on the device.

Push messages can be cast as voicemail/missed_call/user_push and incoming call

Relevant PRs
https://github.com/2600hz/kazoo-crossbar/pull/495
https://github.com/2600hz/kazoo-callflow/pull/217

2023-08-10 16:08 UTC, nkarunarathne commented on src/pusher_listener.erl
> +add_kazoo_device_id(JObj, Device) ->
You can pass only the device id instead of whole device doc. 
@jamesaimonetti right?

2023-08-10 19:46 UTC, Navoda626 commented on test/pusher_listener_tests.erl
> +                        ,kz_json:get_value([<<"Data">>,<<"utc_unix_timestamp_ms">>], EPReq)}
If you know the type of the output of kz_json:get_value/2 earlier (for example binary output), its better to use kz_json:get_binary_value/2 instead. 

And its better. to move } at the end to the next line

2023-08-23 13:37 UTC, wdhammika commented on test/pusher_listener_tests.erl
> +                        ,kz_json:get_value([<<"Data">>,<<"utc_unix_timestamp_ms">>], EPReq)}
Fixed

2023-08-28 21:39 UTC, jamesaimonetti requested changes
Your branch is not rebased to latest master. Please rebase and correct the conflicts

2023-08-29 16:30 UTC, closed without merging